apiVersion: v1
kind: Pod
metadata:
  labels:
    app: configmap-reload
  name: configmap-reload
spec:
  containers:
    - image: configmap-reload:latest
      name: configmap-reload
      ports:
        - containerPort: 8080
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /opt/article-protection-config
          name: article-protection-config-volume
  volumes:
    - name: article-protection-config-volume
      configMap:
        name: article-protection-config
  restartPolicy: Never
                  
          
                
