apiVersion: v1
kind: Pod
metadata:
  labels:
    app: config-demo
  name: config-demo
spec:
  containers:
    - image: config-demo:latest
      name: config-demo
      ports:
        - containerPort: 8080
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /opt/article-protection-config
          name: article-protection-config-volume
  volumes:
    - name: article-protection-config-volume
      configMap:
        name: article-protection-config
  restartPolicy: Never
                  
          
                
