apiVersion: v1
kind: Pod
metadata:
  labels:
    app: configmap-reload
  name: configmap-reload
spec:
  containers:
    - image: configmap-reload:1
      name: configmap-reload
      ports:
        - containerPort: 8080
      imagePullPolicy: IfNotPresent
      env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes,override
      volumeMounts:
        - mountPath: /opt/article-protection-config
          name: article-protection-config-volume
        - mountPath: /opt/mounted-config-map
          name: mounted-config-map-volume
  volumes:
    - name: article-protection-config-volume
      configMap:
        name: article-protection-config
    - name: mounted-config-map-volume
      configMap:
        name: mounted-config-map
  restartPolicy: Never
                  
          
                
